# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
