# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20171125_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
