# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compiler',
            old_name='code_name',
            new_name='codename',
        ),
        migrations.AlterField(
            model_name='compiler',
            name='compile_string',
            field=models.CharField(max_length=255, default=''),
        ),
        migrations.RemoveField(
            model_name='compiler',
            name='compile_string',
        ),
        migrations.AddField(
            model_name='compiler',
            name='runner_codename',
            field=models.CharField(max_length=32, default='native'),
            preserve_default=False,
        ),
    ]
