# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_compiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
