# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_add_new_tester_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='highlighter',
            field=models.CharField(default='text', max_length=32),
            preserve_default=False,
        ),
    ]
