# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_compiler_highlighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemincontest',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_in_contest_set', to='core.Problem'),
        ),
    ]
