# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_change_pic_problem_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_in_contests',
                'get_latest_by': 'created_at',
                'verbose_name_plural': 'users in contest',
                'default_related_name': 'user_in_contest_set',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='is_registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userincontest',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_contest_set', to='core.Contest'),
        ),
        migrations.AddField(
            model_name='userincontest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_contest_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
