# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20170321_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registered_users',
            field=models.ManyToManyField(through='core.UserInContest', to=settings.AUTH_USER_MODEL),
        ),
    ]
