# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contest_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_unfrozen',
            field=models.BooleanField(default=False),
        ),
    ]
