# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:49
from __future__ import unicode_literals

from django.db import migrations


def unfreeze_everything(apps, schema_editor):
    Contest = apps.get_model('core', 'Contest')
    db = schema_editor.connection.alias
    Contest.objects.using(db).update(is_unfrozen=True)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_contest_is_unfrozen'),
    ]

    operations = [
        migrations.RunPython(unfreeze_everything, migrations.RunPython.noop),
    ]
