"""
Django settings for lerna project.
Generated by 'django-admin startproject' using Django 1.8.2.
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def init_logging(cnf):
    import logging
    import logging.config

    if 'handlers' in cnf:
        for handler in cnf['handlers'].values():
            if 'filename' in handler:
                os.makedirs(os.path.dirname(handler['filename']), exist_ok=True)

    logging.logThreads = logging.logProcesses = False
    return logging.config.dictConfig(cnf)


def _init_settings():
    import contextlib
    import yaml

    adjust_path = lambda loader, node: os.path.join(BASE_DIR, loader.construct_scalar(node))
    yaml.add_constructor('!path', adjust_path)
    for filename in ('settings.yml', 'local_settings.yml'):
        with open(os.path.join(BASE_DIR, 'lerna', filename)) as f:
            for key, value in yaml.load(f).items():
                if key == 'PREPEND':
                    for key, value in value.items():
                        globals()[key] = value + globals()[key]
                elif key == 'APPEND':
                    for key, value in value.items():
                        globals()[key] += value
                elif key == 'OVERRIDE':
                    for cnf, sub in value.items():
                        cnf = globals()[cnf]
                        for key, value in sub.items():
                            cnf[key] = value
                else:
                    globals()[key] = value


_init_settings()
